::python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_30_rand_52294052 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_30_rand_52294052 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_30_rand_52294052 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_33_rand_31156631 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_33_rand_31156631 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_33_rand_31156631 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_33_rand_31156631 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_37_rand_68202811 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_37_rand_68202811 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_37_rand_68202811 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_37_rand_68202811 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_22749617 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_22749617 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_22749617 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_22749617 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_26143502 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_26143502 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_30462326 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_30462326 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_30462326 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_30462326 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_80925533 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_80925533 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_80925533 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_40_rand_80925533 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_1420673 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_33305124 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_33305124 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_33305124 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_33305124 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_88686872 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_88686872 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_88686872 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_41_rand_88686872 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_42260169 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_42260169 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_42260169 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_42260169 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_71070565 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_71070565 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_71070565 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_43_rand_71070565 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_42654048 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_42654048 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_42654048 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_42654048 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_95673383 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_95673383 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_95673383 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_50_rand_95673383 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_52_rand_67168905 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_52_rand_67168905 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_52_rand_67168905 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_52_rand_67168905 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_49828134 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_49828134 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_49828134 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_49828134 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_60941079 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_60941079 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_60941079 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_60941079 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_8177102 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_8177102 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_8177102 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_53_rand_8177102 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31116440 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31116440 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31116440 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31116440 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31429249 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31429249 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31429249 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_54_rand_31429249 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_56_rand_78265249 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_56_rand_78265249 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_56_rand_78265249 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_56_rand_78265249 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_58_rand_12506230 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_58_rand_12506230 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_58_rand_12506230 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_58_rand_12506230 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_59_rand_66215675 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_59_rand_66215675 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_59_rand_66215675 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_59_rand_66215675 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_84_rand_360077 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_84_rand_360077 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_84_rand_360077 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_84_rand_360077 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_85_rand_24984722 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_85_rand_24984722 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_85_rand_24984722 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_85_rand_24984722 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_87_rand_17960052 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_87_rand_17960052 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_87_rand_17960052 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_87_rand_17960052 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_90_rand_96487658 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_90_rand_96487658 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_90_rand_96487658 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_90_rand_96487658 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_91_rand_11009960 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_91_rand_11009960 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_91_rand_11009960 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB chris_raw --puzzle_num numPieces_91_rand_11009960 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise