python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_97405629 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_97405629 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_97405629 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_97405629 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_33_rand_15397192 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_33_rand_15397192 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_33_rand_15397192 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_33_rand_15397192 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_34_rand_30489503 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_34_rand_30489503 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_34_rand_30489503 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_34_rand_30489503 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_35_rand_56103127 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_35_rand_56103127 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_35_rand_56103127 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_35_rand_56103127 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_42750708 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_42750708 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_42750708 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_42750708 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_58366427 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_58366427 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_58366427 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_36_rand_58366427 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_44648813 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_44648813 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_44648813 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_44648813 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_66919605 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_66919605 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_66919605 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_66919605 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_79088896 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_79088896 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_79088896 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_37_rand_79088896 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_56665269 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_56665269 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_56665269 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_56665269 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_77398759 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_77398759 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_77398759 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_38_rand_77398759 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_23522205 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_23522205 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_23522205 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_23522205 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_46441001 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_46441001 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_46441001 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_46441001 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_735508 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_735508 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_735508 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_735508 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_78149113 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_78149113 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_78149113 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_39_rand_78149113 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_40582052 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_40582052 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_40582052 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_40582052 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_50045551 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_50045551 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_50045551 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_50045551 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_8799866 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_8799866 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_8799866 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_40_rand_8799866 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_36332819 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_36332819 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_36332819 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_36332819 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_58132176 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_58132176 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_58132176 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_58132176 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_66317330 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_66317330 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_66317330 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_41_rand_66317330 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_6534528 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_6534528 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_6534528 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_6534528 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_91397658 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_91397658 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_91397658 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_91397658 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_94135339 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_94135339 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_94135339 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_42_rand_94135339 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_45_rand_92422041 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_45_rand_92422041 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_45_rand_92422041 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_45_rand_92422041 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_49_rand_99283426 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_49_rand_99283426 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_49_rand_99283426 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_49_rand_99283426 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_75_rand_18322987 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_75_rand_18322987 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_75_rand_18322987 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_75_rand_18322987 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46360408 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46360408 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46360408 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46360408 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46993616 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46993616 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46993616 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB gloria_raw --puzzle_num numPieces_78_rand_46993616 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise