python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 1 (only 2 3 4 staged but backed) --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 10 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 11 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 12 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 13 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 13 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 13 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 13 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 14 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 14 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 14 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 15 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 16 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 16 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 16 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 16 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 17 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 17 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 17 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 17 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 17 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 18 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 18 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 18 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 18 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 19 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 20 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 21 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 22 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 23 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 24 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 24 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 24 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 24 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 24 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 25 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 25 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 25 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 25 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 26 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 26 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 26 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 26 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 26 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 27 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 28 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 28 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 28 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 28 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 29 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 29 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 29 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 29 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 29 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 3 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 30 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 30 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 30 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 30 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 31 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 32 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 33 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 4 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 4 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 4 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 5 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 5 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 5 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 5 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 5 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 6 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 6 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 6 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 6 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 6 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 7 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 7 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 7 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 7 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 8 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 9 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 9 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST2_excluded --puzzle_num 9 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise