python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 1 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 2 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 3 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 4 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 4 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 4 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 4 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB PAST4_excluded --puzzle_num 5 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise