python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_40593844 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_40593844 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_40593844 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_40593844 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_99254258 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_99254258 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_99254258 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_39_rand_99254258 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_78338919 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_78338919 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_78338919 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_78338919 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_85920016 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_85920016 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_85920016 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_41_rand_85920016 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_43_rand_99474430 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_43_rand_99474430 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_43_rand_99474430 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_43_rand_99474430 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_38206916 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_38206916 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_38206916 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_38206916 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_58254682 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_58254682 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_58254682 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_50_rand_58254682 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_33985014 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_33985014 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_33985014 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_33985014 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_45904415 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_45904415 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_45904415 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_51_rand_45904415 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_10664302 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_10664302 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_10664302 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_10664302 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_6079075 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_6079075 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_6079075 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_54_rand_6079075 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_55_rand_56740689 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_55_rand_56740689 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_55_rand_56740689 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_55_rand_56740689 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_56_rand_28249306 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_56_rand_28249306 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_56_rand_28249306 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_56_rand_28249306 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_45672859 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_45672859 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_45672859 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_45672859 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_732647 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_732647 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_732647 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_57_rand_732647 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_19447672 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_19447672 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_19447672 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_19447672 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_76888803 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_76888803 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_76888803 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_76888803 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_772939 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_772939 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_772939 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_58_rand_772939 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_44351463 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_44351463 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_44351463 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_44351463 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_61881184 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_61881184 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_61881184 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_59_rand_61881184 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_16345157 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_16345157 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_16345157 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_16345157 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_46354258 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_46354258 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_46354258 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_46354258 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_67177371 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_67177371 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_67177371 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_67177371 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_73704059 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_73704059 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_73704059 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_73704059 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_80714957 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_80714957 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_80714957 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_60_rand_80714957 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_17760712 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_17760712 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_17760712 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_17760712 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_30657557 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_30657557 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_30657557 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_30657557 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_31605778 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_31605778 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_31605778 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_31605778 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_51789234 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_51789234 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_51789234 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_51789234 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_86235871 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_98655999 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_98655999 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_98655999 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_61_rand_98655999 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_67216148 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_67216148 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_67216148 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_67216148 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_84760675 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_84760675 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_84760675 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_84760675 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_98473484 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_98473484 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_98473484 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_62_rand_98473484 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_24846232 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_24846232 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_24846232 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_24846232 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_2683921 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_2683921 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_2683921 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_2683921 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_96153256 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_96153256 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_96153256 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_63_rand_96153256 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_17173112 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_17173112 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_17173112 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_17173112 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_49566947 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_49566947 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_49566947 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_49566947 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_51275064 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_51275064 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_51275064 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_51275064 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_61868797 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_61868797 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_61868797 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_61868797 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_99640092 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_99640092 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_99640092 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_64_rand_99640092 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_65_rand_44515549 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_66_rand_94893013 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_66_rand_94893013 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_66_rand_94893013 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_66_rand_94893013 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_22619031 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_22619031 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_22619031 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_22619031 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_54516217 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_54516217 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_54516217 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_54516217 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_58593598 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_58593598 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_58593598 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_68_rand_58593598 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_62683649 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_62683649 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_62683649 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_62683649 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 4 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 5 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_69_rand_83619072 --noise_level 6 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_70_rand_64140743 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_70_rand_64140743 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_70_rand_64140743 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_70_rand_64140743 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_54691221 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_54691221 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_54691221 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_54691221 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_77945842 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_77945842 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_77945842 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_72_rand_77945842 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_73_rand_92405561 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_73_rand_92405561 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_73_rand_92405561 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_73_rand_92405561 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_74_rand_30465410 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_74_rand_30465410 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_74_rand_30465410 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_74_rand_30465410 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_76_rand_45233565 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_76_rand_45233565 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_76_rand_45233565 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_76_rand_45233565 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_78_rand_49983051 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_78_rand_49983051 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_78_rand_49983051 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_78_rand_49983051 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_81_rand_78371098 --noise_level 0 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_81_rand_78371098 --noise_level 1 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_81_rand_78371098 --noise_level 2 --is_stage --is_no_erased_pieces_by_noise
python scripts\puzzle_solution_to_physics.py --DB sirsimo --puzzle_num numPieces_81_rand_78371098 --noise_level 3 --is_stage --is_no_erased_pieces_by_noise